version: '2'
services:
  visiocam-app:
    image: visiocam
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://visiocam-postgresql:5432/visioCam
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://visiocam-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://visiocam-elasticsearch:9200
    ports:
      - 8080:8080
  visiocam-postgresql:
    extends:
      file: postgresql.yml
      service: visiocam-postgresql
  visiocam-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: visiocam-elasticsearch
